### ISSUE TITLE
Different version is shown when use `-v` option

### ISSUE THREAD

**Issue by y0za** [diginatu/nagome#11]
I downloaded nagome v0.0.5 binary from GitHub Releases.
But `nagome -v` showed version which is different from expected version.

## Expected behavior
`nagome -v` result is `Nagome   v0.0.5`

## Actual bahavior
`nagome -v` result is `Nagome   v0.0.3-47-g292b02d`

## Possible fix
Version text comes from `git describe --tags` ([Makefile](https://github.com/diginatu/nagome/blob/aa12cc426bb6626cfaba46846102d84dccd0e2c6/Makefile#L5))
It seems that released binary was built before v0.0.5 tag, and it contains unnecessary information (number and commit hash).
So I think building after v0.0.5 tag and replacing the command with `git describe --tags --abbrev=0` will work.

**Comment by diginatu** [comment]
Sorry, actually I know this issue.

The problem was that I created a lightweight tag for v0.0.5 which doesn't affect the version number in the result of command `git describe`.
I fixed it by just adding an `--tags` option in this commit aa12cc426bb6626cfaba46846102d84dccd0e2c6.
So the Makefile you saw was the fixed version of the command.

I have to create one more new tag for updating this fix.

Anyway, thank you for your reporting.

**Comment by y0za** [comment]
>The problem was that I created a lightweight tag for v0.0.5 which doesn't affect the version number in the result of command git describe.
>I fixed it by just adding an --tags option in this commit aa12cc4.

Sounds good👍 

However as mentioned above, `git describe --tags` result contains unnecessary information.
For example, the result should be `v0.0.5`, but actual result is `v0.0.5-1-gaa12cc4`.
I think that the correct result will be obtained by adding `--abbrev=0` option.

**Comment by diginatu** [comment]
I want a make it possible to identify the binary created from the code that isn't on any tag.
You can still get the result `v0.0.5` from the command without `--abbrev=0` when you are exactly on the tag.

```
$ git describe --tags
v0.0.5-1-gaa12cc4
$ git checkout v0.0.5
Note: checking out 'v0.0.5'.
HEAD is now at 292b02d... fix wasn't able to compile in windows
$ git describe --tags
v0.0.5
```

**Comment by y0za** [comment]
OK, I finally understand.
